---
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:QuTHEuYJr5tHLVghVRQ4n6XT4CaR9KfKp+qzfEmq5WzFh/7Fn+ja+9fYcqSMm+ScD9AMrxQWB+ODpCjtKqJ29xrd7+EaYROPU1c=,iv:Xt/UtHdVharHtYKgVM6r7cpLa3si07PfgKXzqdMcvss=,tag:8ynwTPyIlT+MdXaXgnINwQ==,type:str]
sops:
  age:
    - recipient: age19tvjegxtk6e4gef3km9ns96uhhhvdrda3n04kv0g5sf0mggal40shfwzc9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSEczWGp4N1F1dEZNU1VB
        aytCRUVmSElVYjBhSEpjd3g1RVRDMzNXenlrCkIwc09TYVJ0NUpoT3RTaE5MZm5O
        OHJqUUwxRnR3bk4vb2JiSzFsNGZ0a1EKLS0tIHVDc2NsTTY4cVQzenAzNXpXOU1t
        YURHS0xMTTR6MmdOVUdlcG9XQ2d1UGMKqTVT4by87aCx0bsXjKy6O9pb6zqXnCU6
        LlU5K/O++BahlJqJdlLJDnbdTDV1w/bJoAX2wqW77cuZuQnVD6jUKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-31T04:05:01Z"
  mac: ENC[AES256_GCM,data:1gV1HCxsJbbdKQCu6mzOgVr32sInwNuibV1fRJjyH/VVqpfjxJx3pXF3yetKKvehUYXrsuF2PnX56zOlLACzz901thNbhWuyHfCIjKvToACt5XKFoGPIGI/OZ0R2Z3z+uuukSytIO5KBD/ZBDZlsdFrUHH9uFf+zhzsfd5FWPDs=,iv:icbXfY61ivpYqe52v2LbJDcBJvU833mco2D+wVrpc/I=,tag:C1s0x3B4oG7RE/AMrA44ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2

