---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      minio:
        strategy: Recreate
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/minio/minio
              tag: latest
            command: ["/bin/sh","-c"]
            args:
              - |
                exec /usr/bin/minio server /data \
                  --console-address :9001
            envFrom:
              - secretRef:
                  name: minio-root
              - secretRef:
                  name: minio-oidc
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: 9000
                  periodSeconds: 10
                  timeoutSeconds: 2
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/ready
                    port: 9000
                  periodSeconds: 10
                  timeoutSeconds: 2

    service:
      app:
        controller: minio
        ports:
          http:
            port: 9000
          console:
            port: 9001

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 200Gi
        globalMounts:
          - path: /data

    serviceMonitor:
      app:
        enabled: false
