---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-cnpg-user
  labels:
    app.kubernetes.io/name: minio
spec:
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: docker.io/minio/mc:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: minio-root
            - secretRef:
                name: minio-cnpg-user
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              mc alias set minio http://minio.minio.svc.cluster.local:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              # Create or update policy for cnpg backups
              cat > /tmp/cnpg-policy.json <<'POL'
              {
                "Version": "2012-10-17",
                "Statement": [
                  {"Effect": "Allow", "Action": ["s3:ListAllMyBuckets"], "Resource": ["arn:aws:s3:::*"]},
                  {"Effect": "Allow", "Action": ["s3:ListBucket", "s3:GetBucketLocation"], "Resource": ["arn:aws:s3:::cnpg-backups"]},
                  {"Effect": "Allow", "Action": ["s3:PutObject","s3:GetObject","s3:DeleteObject","s3:AbortMultipartUpload","s3:ListBucketMultipartUploads"], "Resource": ["arn:aws:s3:::cnpg-backups/*"]}
                ]
              }
              POL
              mc admin policy create minio cnpg-backups-policy /tmp/cnpg-policy.json || true
              # Create user or update its credentials
              if ! mc admin user info minio "$MINIO_CNPGBK_USER" >/dev/null 2>&1; then
                mc admin user add minio "$MINIO_CNPGBK_USER" "$MINIO_CNPGBK_PASSWORD"
              else
                mc admin user set minio "$MINIO_CNPGBK_USER" password="$MINIO_CNPGBK_PASSWORD"
              fi
              mc admin policy attach minio cnpg-backups-policy --user "$MINIO_CNPGBK_USER"
              echo "MinIO user '$MINIO_CNPGBK_USER' ensured with policy 'cnpg-backups-policy'"

