apiVersion: v1
kind: Secret
metadata:
  name: minio-oidc
  namespace: minio
type: Opaque
stringData:
  #ENC[AES256_GCM,data:nNTz0jxxMrwufJtbK38p1ddNcRw=,iv:zlFjttpYprWOuQesGEkgSmi9t9vrJ6g0yXRawwhqTck=,tag:PzkY59iHBuYDFs50lQBI8g==,type:comment]
  #ENC[AES256_GCM,data:YB3M0gNqfKddQdV3/YzTKmNTo9mYf/12gTmV1AoD+T0ck+PdqX0An3mo0rRoRQZpj2uyhDhbQ5+b,iv:NL+evA5VUDWdtYdcd0reuIZtfGupKUmbzeOx1OyVQmc=,tag:aZbkR5R1GBIEgqgqE08cHQ==,type:comment]
  #ENC[AES256_GCM,data:/vFzvtVO2L80FilWmT2tyQccEcKzw13kYTQckbHUv57aArfKDqEwRL7Ym13NmVWb,iv:xPhN9MtYdnrKOiiyxVDz81mHN7HeeeXbKySszWur2qM=,tag:2vD1XMyleZIH2G8Hj/1Wxg==,type:comment]
  #ENC[AES256_GCM,data:num001tYI8qH8mGvMEEtkRWWJrFjpQD9DoCMgMJ7VaxQ,iv:JMExd8ssvJP0uXgXKNGEOfyD04g8igXJDP+LGHMgNYc=,tag:/g/xd1mpaz+E7OrRrrU6dw==,type:comment]
  MINIO_IDENTITY_OPENID_CONFIG_URL: ENC[AES256_GCM,data:Wv5IlOjQ9M0+jA4ek0MaKnDN5JebOsSyZa/Qk6Rhz6wWktrigQw40KoKMfKuJYkzp0oY0nYijT/75vd8fG1lAEDo7n7cmzpxJQuSoE4PuFBDSA==,iv:cR1HhoTdgdL3hVQAOuaFneNYfK5p/QyPm6ayd+5RP+E=,tag:XWmZpJif3WstbpiKN4UWjQ==,type:str]
  MINIO_IDENTITY_OPENID_CLIENT_ID: ENC[AES256_GCM,data:sCUd0pKkj/f4D7zSSnQPjwngeEjyXIHA6SLEE2r7QIHEpaog/3G4Kw==,iv:WfNIlF66YHcIy6D5zB5fhFKd/ZgRAHz8sO58S45RX6g=,tag:Ygv6DpjSG+6Rb9RgBjP+mw==,type:str]
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:fdzQ3NLddhiJjSCAAQxTkkPm2zodKvKiCm9cB6jWrcCZHn4rfOonexdo6oJx13UoN5PqmY4rV332KJSDnOekg9CCM7hJ7kNj2dNy9yT34Q+VWAl7cJ3sshScvuYY+xmQUK/eGV0HDlNJGmw8yYzC4FJmbZX/xHpdlIsmaqEKe6M=,iv:oJlvKrQsZ5EHESQWseixP3BC9oPJH1MoRqMUtqoWCdg=,tag:hpRWo6F0nYkbUOQrFtX56A==,type:str]
  MINIO_IDENTITY_OPENID_REDIRECT_URI: ENC[AES256_GCM,data:xkPUsRKIk1lDFsRxv44FlnpxjfSNCvYrxo6A+lBelCvwyud6cCXySNAn/hob,iv:FvYXPzpx3JWaquHxFcxXo8GjXUhDZU+YDKCfkA7ZPs4=,tag:e+rxPp6YfvgmqkoW6uBY4Q==,type:str]
  MINIO_IDENTITY_OPENID_SCOPES: ENC[AES256_GCM,data:HQn2sH6EWQAn6S7V882hjHnDdfA=,iv:J/4tNjYITf5R61p13XO/rnBGxwg+cp1WZwJpTPzmboQ=,tag:IEZY6zoVJy+rTEUWudUIbQ==,type:str]
  #ENC[AES256_GCM,data:Dpr0cjAvA4dfqvktWEs1GMOJ5ozPaS5+HMCiP/fEbrb/zSBV+bxyLqEXaH52MaTaNjZHJ/rqINEAHTzqTGk=,iv:AKL43uAm02i9SercxtoQm2mP2s4/mlq6EFSfAROiFmM=,tag:utFzpeVg3gf40Pw5smkEhg==,type:comment]
  #ENC[AES256_GCM,data:JdNVlA1Vg675rdgPVIciBf68N25O5PgBGxk7g1N9QmE3/5JMUln8gZl9,iv:tszqZb6oqi2HXiuIgzznaEW+kg0UyEIE2cfttiawnRE=,tag:bLirOBCV7ZJzCG+GuKUP5Q==,type:comment]
  #ENC[AES256_GCM,data:1odtse+HqZAfDLRIrP/CfLCoTGpozF+xCNI6F/6Sc6AufFwuSbN3,iv:gxWLX/hl/23xhZS8HkPUlB1FM594zvzF0WR2WLo+oxI=,tag:PZvmq18IuEXl6+qiVA6wtA==,type:comment]
sops:
  age:
    - recipient: age19tvjegxtk6e4gef3km9ns96uhhhvdrda3n04kv0g5sf0mggal40shfwzc9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdTh1ekF2VzUrajg4ZEho
        Z2pEa29qK1RyazJLWDVCa1c0Rnk2OVlFMDJBCjViNC9oTzJPcnQ4aGt1OFVWQ3FQ
        Mk83SHo1dnF6Ukp2b1lLQmZDKy9YaGcKLS0tIGZVZjVaNEI3L3FnU2Z3RFRuMlVQ
        VTRpNlQ0aDlSbEpjLzJXSFA0ZGkvZFkKOfShcoEgpaAMiC79yc8q1Vt7phnPs/sD
        G5SpgxSjZbMeTeSejbhBhDJbHPLnrlAWv/hBNnaZyDwO3XCWi3sEtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T19:36:15Z"
  mac: ENC[AES256_GCM,data:qMQkkpcnNyVezimN4IFET7OlGZF5GwZaBu28GOyHEeGaTcqfCyQZoQGvkH7EfsAv5ykKMItgIcdooDPuEfJiz1vHKllNB4nMsMAdtYP+jxeG9CHYrt1TBzXv0aoRNMwJi4j5ZEN/PBADOSNx6Co4LMb1QR1N5b2sbqz8LIejKdo=,iv:z40i/RwMnzbYCuCtWyyHLDBgfuZb03EVEibL0q8clQM=,tag:Y1noG+aMHnjHfqJMsVhQjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
