apiVersion: v1
kind: Secret
metadata:
  name: minio-oidc
  namespace: minio
type: Opaque
stringData:
  # OIDC with Authentik
  # Configure an application in Authentik with redirect URI:
  #   https://minio.${SECRET_DOMAIN}/oauth_callback
  # and scopes: openid profile email
  MINIO_IDENTITY_OPENID_CONFIG_URL: https://auth.${SECRET_DOMAIN}/application/o/.well-known/openid-configuration
  MINIO_IDENTITY_OPENID_CLIENT_ID: "CHANGE_ME"
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: "CHANGE_ME"
  MINIO_IDENTITY_OPENID_REDIRECT_URI: https://minio.${SECRET_DOMAIN}/oauth_callback
  MINIO_IDENTITY_OPENID_SCOPES: "openid,profile,email"
  # Optional: map claim for username / policy matching if desired
  # MINIO_IDENTITY_OPENID_CLAIM_NAME: "email"
  # MINIO_IDENTITY_OPENID_CLAIM_PREFIX: ""
