apiVersion: v1
kind: Secret
metadata:
  name: minio-oidc
  namespace: minio
type: Opaque
stringData:
  #ENC[AES256_GCM,data:+e8VLC2bFFaxV183651Vje5jqfE=,iv:jQi4VmdcJkyzKk3zeK97YN/mZvhcmUCLzrQTkmsF0vU=,tag:eYbHwP/md3fCD9c052Ky8A==,type:comment]
  #ENC[AES256_GCM,data:AQ2c31kgr1lHhXHzTnjTYzKwWc3F9LRT3+919Mw1wjiRoSWQblgT1zSLGPjrSCL6SK2y1CXM1dSO,iv:Dbs0EUysY/PP/C+sFxU6h38ziYXFt9lc5yJU8FZ9S1w=,tag:NznIvyPHTBCN6Mu8e9hnmA==,type:comment]
  #ENC[AES256_GCM,data:sLWnoDhehnYBXR2RVGSTLeaartCszUODieK64AEt+4kmF8dPZ3CcH9vKaSnS92ro,iv:+YpThKEVhg5BvtrPpf/ABtWmDjXSw6+aeScuySdrFbE=,tag:AVV6HW3UemWjuEGS67d5xA==,type:comment]
  #ENC[AES256_GCM,data:03/Vim7+6Xi2/dIrEj6t2VQ/iPjYIxrpXNiAFjJHV2I2,iv:ZDlCuvwLoyP8TCRIHanlX+YIIVI2XCEEHVcurxQtnQs=,tag:xrySXqJWw5dD2Loriq7oew==,type:comment]
  MINIO_IDENTITY_OPENID_CONFIG_URL: ENC[AES256_GCM,data:BsN1aBQbPzVIHF+83HnWa1XbpIrPMv6/rVfV6iI6alIybeTCS6iUlTjm1fQ3MFUA0ghIc61iziWLdlS2LRYbfETbQDY7q88HqLmI+6jeiXR5YD7Sb7+LfQ==,iv:53B8Kkh7G8iGDrLMHq5VrdzkW9W9/3X8pqN41gdVp0s=,tag:lnhyzlppa3uKd4ZzSfBYCg==,type:str]
  MINIO_IDENTITY_OPENID_CLIENT_ID: ENC[AES256_GCM,data:SBxRXT4mNAlmkT8wkZTTFZkCxXl1QAFOTQD7TsVBlt+7jJ7dv9TE4A==,iv:xpKBgSlCY8YWnIscCqnKNgWyvCJQ3Vp49HPZ/b9p+ls=,tag:FYwfnQ6qjaRvfZ0HoBnnmQ==,type:str]
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:u/lsNFQqAcJnyLO8HAIjnHxav5S4qZzcLq7Nku8nlK2lmAVGf5fo1WLBZYHv6MyoQ4cp4dYGdcQmuIUXz+Fqx51EAAbYUZb0qHzD7Hju0cKObQ41G/+5psjW0v4Gw0lTbGGEiqjH7AUCSe59WmHZp2IloKQMw4iwvuu1lKeDqMo=,iv:ZOvu75soM2KA1Z/siQzBEo6umahXQ+y+CqaVjNsp2Uc=,tag:wPKew2R02Oa5FPCWPHKzJQ==,type:str]
  MINIO_IDENTITY_OPENID_REDIRECT_URI: ENC[AES256_GCM,data:eKEwCdrTR8T2Dd1VEGAkjoZlHYkUaN7SsI1npHT1/iDhgeaynEV7xR9LgQd+KRKqiA64,iv:4K0Nyjo4UY0Y+PcXPA8xjx5tX7kKAvLVSFC1CAiUtQY=,tag:fa+yx8xmkx9LvzslQEnNNw==,type:str]
  MINIO_IDENTITY_OPENID_SCOPES: ENC[AES256_GCM,data:ljWwTIYKdt+6IwfwF6w/I9pweQ0=,iv:aHOqYrIX+AnSaIRVx7SuE4P02Yb7sNIxeRDdARTBHXw=,tag:ABN1T01CRtw2oomYlQkVtQ==,type:str]
  #ENC[AES256_GCM,data:1IKJtQRY06r2mnXUrfYMO7jvCXYC0jtLdnZPMvmRQe3vRHn50wTHCApzwaVm+3uSSSSvADV2U155z1w1IAE=,iv:UesVwSATtf9g8PzuS91eTqdb8JJRdC6IbUcJfS+e5Ik=,tag:4eBHBA89V2bOzioJrprSLA==,type:comment]
  #ENC[AES256_GCM,data:zaBJR34OKKeoJXBk+Lxrx30UnaSZkabXL5FQfDN6zEun64138ysN/w1u,iv:DSLbDK75zJpAPoWr8kwsa/38Zrhoj/TUVXDaFtUkjgE=,tag:Mj238W+7u2FISdBRg/p12A==,type:comment]
  #ENC[AES256_GCM,data:ZCo6asha1U+mxCTH2wYot0NWk4ubQCgavnLLvMCBDT2mgDHlzWM1,iv:q3xEpSPxn98pJiVmDOsSJqjXmOv+0cC/GAYvTShtSCY=,tag:wKLRzliAsk84JbeGMvWjSA==,type:comment]
sops:
  age:
    - recipient: age19tvjegxtk6e4gef3km9ns96uhhhvdrda3n04kv0g5sf0mggal40shfwzc9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SjlrZjdMZW1hQXEzeUhT
        WTd1N3BFMStYL2U0Q3lBcHJqSkhQQm0rK3dBClY0M0Z1bWJwN0NBSGNBZnBmUm9P
        R1dPV1VoUWRnbTBXZzhFWmtSVmg3NmMKLS0tIFVicHlKSHUrK1NVNFFBS2hPR1pa
        YnNFYXdDS0JGVFptUDZPWWMrZEdHNjgKTHcjrew0yIr4hKHd5Vrou2otK2po7OXr
        rC6XQ8CUFzP824zAdyLudYB84x3JqQoBld7O2yUD1JBoFCpJv1tuSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-02T17:12:12Z"
  mac: ENC[AES256_GCM,data:AvYAlWuOM7r+E0kyCHmB+YlxMMigMZy1QNqg+YVblN4L+tT8y9I2hB8Ya5/C+gPIWSNtvRx3+mseNH9CzXwdPAMp7RBN1zZL9ufGNWG1ij3d1qsHHoK7r7bVEbabN/k8nGSLNstwJy2Nry+WbEQ9oUlsMh9a8FX/rHtqRv2Uijs=,iv:u0BHvdbvJkqLuMRPntOdi013wCa9WBCF3tuN9l2bO4M=,tag:Dqf3dfkyqWrG27Uq5oc0FQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
