---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: 9.4.3
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: Secret
      name: grafana-values
      valuesKey: values.yaml
  values:
    assertNoLeakedSecrets: false
    service:
      type: ClusterIP
      port: 80
    envFromSecret: grafana-env
    persistence:
      enabled: true
      type: pvc
      storageClassName: longhorn
      size: 10Gi
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
