apiVersion: v1
kind: Secret
metadata:
  name: grafana-values
type: Opaque
stringData:
  values.yaml: |-
    adminUser: admin
    adminPassword: "J&2E2qyXqNzzFUH4um2k"
    grafana.ini:
      server:
        root_url: https://grafana.${SECRET_DOMAIN}
        domain: grafana.${SECRET_DOMAIN}
      auth:
        disable_login_form: false
        oauth_auto_login: false
      auth.generic_oauth:
        enabled: true
        name: Authentik
        scopes: openid profile email
        email_attribute_name: email:primary
        login_attribute_path: preferred_username
        name_attribute_path: name
        # These will come from your Authentik OAuth2/OpenID provider for Grafana
        auth_url: https://auth.${SECRET_DOMAIN}/application/o/authorize/
        token_url: https://auth.${SECRET_DOMAIN}/application/o/token/
        api_url: https://auth.${SECRET_DOMAIN}/application/o/userinfo/
        allow_sign_up: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.monitoring.svc.cluster.local:3100
          - name: Tempo
            type: tempo
            access: proxy
            url: http://tempo.monitoring.svc.cluster.local:3200
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            updateIntervalSeconds: 10
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kubernetes-events:
          json: |-
            {
              "id": null,
              "uid": "k8s-events",
              "title": "Kubernetes Events (Loki)",
              "tags": ["kubernetes","events","loki"],
              "timezone": "browser",
              "schemaVersion": 39,
              "version": 1,
              "refresh": "30s",
              "panels": [
                {
                  "type": "logs",
                  "title": "Recent Events",
                  "gridPos": { "x": 0, "y": 0, "w": 24, "h": 16 },
                  "options": {
                    "dedupStrategy": "none",
                    "enableLogDetails": true,
                    "showLabels": false,
                    "wrapLogMessage": true
                  },
                  "targets": [
                    {
                      "refId": "A",
                      "datasource": { "type": "loki", "uid": "Loki" },
                      "expr": "{job=\"kubernetes-event-exporter\"} | json"
                    }
                  ]
                },
                {
                  "type": "bargauge",
                  "title": "Top Event Reasons (1h)",
                  "gridPos": { "x": 0, "y": 16, "w": 24, "h": 10 },
                  "options": {
                    "displayMode": "gradient",
                    "orientation": "horizontal",
                    "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false }
                  },
                  "fieldConfig": { "defaults": { "unit": "short" }, "overrides": [] },
                  "targets": [
                    {
                      "refId": "A",
                      "datasource": { "type": "loki", "uid": "Loki" },
                      "expr": "topk(10, sum by (reason) (count_over_time(({job=\\\"kubernetes-event-exporter\\\"} | json | label_format reason=\\\`Reason\\\`)[1h])))"
                    }
                  ]
                }
              ]
            }
        http-slo-blackbox:
          json: |-
            {
              "id": null,
              "uid": "http-slo-blackbox",
              "title": "HTTP SLO (Blackbox)",
              "tags": ["slo","blackbox"],
              "timezone": "browser",
              "schemaVersion": 39,
              "version": 1,
              "refresh": "30s",
              "panels": [
                {"type":"stat","title":"Grafana uptime 1h","gridPos":{"x":0,"y":0,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"avg_over_time(probe_success{job=\"blackbox-grafana\"}[1h]) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"percentage","steps":[{"color":"red","value":0},{"color":"yellow","value":99.0},{"color":"green","value":99.9}]}}}},
                {"type":"stat","title":"Grafana uptime 6h","gridPos":{"x":6,"y":0,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"avg_over_time(probe_success{job=\"blackbox-grafana\"}[6h]) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"percentage","steps":[{"color":"red","value":0},{"color":"yellow","value":99.0},{"color":"green","value":99.9}]}}}},
                {"type":"stat","title":"Grafana uptime 24h","gridPos":{"x":12,"y":0,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"avg_over_time(probe_success{job=\"blackbox-grafana\"}[24h]) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"percentage","steps":[{"color":"red","value":0},{"color":"yellow","value":99.0},{"color":"green","value":99.9}]}}}},
                {"type":"stat","title":"Grafana uptime 30d","gridPos":{"x":18,"y":0,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"avg_over_time(probe_success{job=\"blackbox-grafana\"}[30d]) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"percentage","steps":[{"color":"red","value":0},{"color":"yellow","value":99.0},{"color":"green","value":99.9}]}}}},

                {"type":"stat","title":"Grafana fast burn err% (5m)","gridPos":{"x":0,"y":6,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"(1 - avg_over_time(probe_success{job=\"blackbox-grafana\"}[5m])) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"absolute","steps":[{"color":"green","value":0},{"color":"yellow","value":0.1},{"color":"red","value":1.0}]}}}},
                {"type":"stat","title":"Grafana slow burn err% (30m)","gridPos":{"x":6,"y":6,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"(1 - avg_over_time(probe_success{job=\"blackbox-grafana\"}[30m])) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"absolute","steps":[{"color":"green","value":0},{"color":"yellow","value":0.1},{"color":"red","value":1.0}]}}}},

                {"type":"stat","title":"Authentik uptime 1h","gridPos":{"x":0,"y":12,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"avg_over_time(probe_success{job=\"blackbox-authentik\"}[1h]) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"percentage","steps":[{"color":"red","value":0},{"color":"yellow","value":99.0},{"color":"green","value":99.9}]}}}},
                {"type":"stat","title":"Authentik uptime 6h","gridPos":{"x":6,"y":12,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"avg_over_time(probe_success{job=\"blackbox-authentik\"}[6h]) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"percentage","steps":[{"color":"red","value":0},{"color":"yellow","value":99.0},{"color":"green","value":99.9}]}}}},
                {"type":"stat","title":"Authentik uptime 24h","gridPos":{"x":12,"y":12,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"avg_over_time(probe_success{job=\"blackbox-authentik\"}[24h]) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"percentage","steps":[{"color":"red","value":0},{"color":"yellow","value":99.0},{"color":"green","value":99.9}]}}}},
                {"type":"stat","title":"Authentik uptime 30d","gridPos":{"x":18,"y":12,"w":6,"h":6},
                 "targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"Prometheus"},
                   "expr":"avg_over_time(probe_success{job=\"blackbox-authentik\"}[30d]) * 100"}],
                 "fieldConfig":{"defaults":{"unit":"percent","thresholds":{"mode":"percentage","steps":[{"color":"red","value":0},{"color":"yellow","value":99.0},{"color":"green","value":99.9}]}}}}
              ]
            }
