apiVersion: v1
kind: Secret
metadata:
  name: grafana-values
type: Opaque
stringData:
  values.yaml: |-
    adminUser: admin
    adminPassword: "J&2E2qyXqNzzFUH4um2k"
    grafana.ini:
      server:
        root_url: https://grafana.${SECRET_DOMAIN}
        domain: grafana.${SECRET_DOMAIN}
      auth:
        disable_login_form: false
        oauth_auto_login: true
      auth.generic_oauth:
        enabled: true
        name: Authentik
        scopes: openid profile email
        email_attribute_name: email:primary
        login_attribute_path: preferred_username
        name_attribute_path: name
        # These will come from your Authentik OAuth2/OpenID provider for Grafana
        auth_url: https://auth.${SECRET_DOMAIN}/application/o/grafana/authorize/
        token_url: https://auth.${SECRET_DOMAIN}/application/o/grafana/token/
        api_url: https://auth.${SECRET_DOMAIN}/application/o/userinfo/
        allow_sign_up: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.monitoring.svc.cluster.local:3100
          - name: Tempo
            type: tempo
            access: proxy
            url: http://tempo.monitoring.svc.cluster.local:3200
