# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:lNPXyWkvFNisIBPzDRXBJ8/kjLE6DIJcazJTOKe0+2U=,iv:gOTwQXYk/piSgurfT3l/D5zOs2gL4wLfugbcUqSD1GY=,tag:h8xQQHAMxVufiYcm+vEcQA==,type:str]
sops:
  age:
    - recipient: age19tvjegxtk6e4gef3km9ns96uhhhvdrda3n04kv0g5sf0mggal40shfwzc9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVVBZeDR4Z1RETmRCSEtG
        elJhblZGSTRpRGxkTEFUNGtIdHAzcGxjM0ZJCi81UjIrM2IwbEVXUm1QbjBnMS93
        NDhPeE9PRmRhekJkZjlCcUp2YktFTmMKLS0tIEV4ZzRHVGhrVTFWaUdTbHpIM05v
        NUs1UnpML0hwd0s0MENiNmhNaTdrOU0K08OAMxlwNcx79EcKT0QM10rjaqqD/sZb
        jXUX2C7soDTAMM9uP4es26BuHlodBFbRGG0kfv3hSrRICBv/Tf2RsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-31T04:05:01Z"
  mac: ENC[AES256_GCM,data:nWOpK1d2iXoGC1rrPHLq4rd+w6+qCve0S/0r1e8AB8bYyiSJBnWsHOHWXCD+IkNaniBzkidrxkpRk2tPeQpJY9V6WwF0NXeSYHCebiz/FCnbhJ1OoPy5K4XWurEtVBJu9c8TmuMiMkgEpTo/F7eCuoSCDeqd9tnY5VTYgNbbq/A=,iv:hzbF/WTWh1SkKUY+8YHFCAAqwSkggfSsCYQL6jFS5ac=,tag:fzyOW3yvH+1lBhUGu9IoOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
