---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keycloak-chart
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
  ref:
    tag: 25.2.0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: keycloak-chart
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    production: true
    proxyHeaders: xforwarded
    hostname: keycloak.${SECRET_DOMAIN}
    postgresql:
      enabled: false
    service:
      type: ClusterIP
      ports:
        http: 80
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    ingress:
      enabled: false
    auth:
      adminUser: admin
      existingSecret: keycloak-admin
      passwordSecretKey: admin-password
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    externalDatabase:
      host: keycloak-db-rw.security.svc.cluster.local
      port: 5432
      user: keycloak
      database: keycloak
      existingSecret: keycloak-db
      existingSecretPasswordKey: password
