---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 1h
  chart:
    spec:
      chart: tempo
      version: 1.23.3
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 20Gi
    tempo:
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo
      compactor:
        compaction:
          retention: 720h
    serviceMonitor:
      enabled: true

