---
apiVersion: batch/v1
kind: Job
metadata:
  name: authentik-promote-admin-v3
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: promote
          image: ghcr.io/goauthentik/server:2025.8.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash","-lc"]
          args:
            - |
              set -euo pipefail
              source /ak-root/.venv/bin/activate
              cd /
              python -m manage create_admin_group || true
              python -m manage shell - <<'PY'
              from authentik.core.models import User, Group
              g = Group.objects.get_or_create(name='authentik Admins')[0]
              targets = list(User.objects.filter(username__in=['admin','akadmin']))
              for u in targets:
                  u.groups.add(g)
                  u.save()
              print('added to admins:', [u.username for u in targets])
              PY
          envFrom:
            - secretRef:
                name: authentik
