---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik-charts
spec:
  interval: 1h
  url: https://charts.goauthentik.io
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2025.8.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: Secret
      name: authentik-values
      valuesKey: values.yaml
  values:
    # Enable built-in dependencies and persistence
    postgresql:
      enabled: true
      auth:
        username: authentik
        database: authentik
      primary:
        persistence:
          enabled: true
          storageClass: longhorn
          size: 8Gi
    redis:
      enabled: true
    server:
      service:
        type: ClusterIP
        servicePortHttp: 80
    # Bootstrap/admin and DB credentials, secret key are provided via valuesFrom secret

