---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
components:
  - ../../components/common
postBuild:
  substituteFrom:
    - kind: Secret
      name: cluster-secrets
resources:
  - ./secrets
  - ./minio/ks.yaml
