apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: security
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Z7sP/LVqxp49XGA=,iv:fJrmLCakkVrFo9cWua75vdoE82a+tWFQSJ7IiZuY1pw=,tag:x0qrL4SRQEsY/NBex2OJeg==,type:str]
sops:
    age:
        - recipient: age19tvjegxtk6e4gef3km9ns96uhhhvdrda3n04kv0g5sf0mggal40shfwzc9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S243ZHJqNFlQdkM2N0pP
            RFpNT2NUelNNYVEyMTIzR0NSYzZiRS9yL0FjCmYvNFprWWtpQ2p3S1B2Y2lmSFhj
            UEQ5VDJSdkpxNmxPMjlEbHZkY2tFQVEKLS0tIFdQa3NGSEZjSjY3eFpjWUJrQkcw
            VjRFM1g5Zk5RaXYra2R6Rjlsd3VJQ00KfF+6g5Hymc1O9Lk03t9F5ADllZp6LXfb
            afu8zBvxSXIDYAgFfCUVcXfz4MKoEErwwyAeGdZc/QCRsABq5a+49g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T12:24:24Z"
    mac: ENC[AES256_GCM,data:vMI2wdq1TIvbfSUPQWlOX14vZRqhXM4ADa7TH7my4lmjQatQnPf/pYqYjW8Z4BFwkwJRV1NjQ6K20al3tXGgWA67477BWA7wMR8Nl7qDVxxr4NVG4l7ZyTOxI+aNQWHiiqjE4bye3RQwYyDkYG6jAJ2lYmVMsdwm8KX6JpNS4rU=,iv:ejPFTiEwq91syPesPGQtaLd7tfrrwjsmArB8XfLJi80=,tag:1+zDF4XQ6RwHs5VJQUADjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
