apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: security
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:PE8serLTn+EMhwk=,iv:RhTL4QsQ7nVZyi8LRUUh3X5ST9Qj96mTMPMIjq45C1I=,tag:XLgRdZLgrflHC67sRoLAmg==,type:str]
  admin-user: ENC[AES256_GCM,data:sIFOGmY=,iv:EJovYwn21zIjfB65Q5CycT/WPRnx/1M77zcG4ZEazEc=,tag:QHyvk/Ix5qg6WC2A9rfrgA==,type:str]
sops:
  age:
    - recipient: age19tvjegxtk6e4gef3km9ns96uhhhvdrda3n04kv0g5sf0mggal40shfwzc9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN0RkWWFoMmlkK01KTlVP
        aHZuOFpDQ2k4VUUvU1RYMFNZNGl5dFNncGk0CjYvei81dER0WXhQajkvSDQybGc1
        VW1qSWJpbnk1c0NLSlJ4RE9IZklwZXMKLS0tIHdCRTF3cnZlVHdjNnhraDhkNTQr
        Y1daeUQ1MjhFclU2clN5ZDdlKy9TaWsKq6S+aW/imeBr9M18HJSDbrMpNR/o5KFi
        5KV8uUM7/2t8Z/z9rxVZKESOMJ3TX2cloTyyeb5Uu0Gim49UwQnFxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-02T15:54:51Z"
  mac: ENC[AES256_GCM,data:q9axCOAtvVZ1rJnHbyQ4uLukkniszpLyHzzS8IN/rOJjzmntVR254riQYY9E8GmUGB8qldkBV2fSPxTFwoaVwolH122+qG2xntPrKwnss7Pp66q0kTDLNoTVFcnxUIWjZD4Kt9Tf/9sOsoARdD2ENPqiZGseBGuB8+oX29wqGos=,iv:afjdwGVyUs9lzpe1Y+Kl1JCBdpU2VqV+2VJ1eNloPws=,tag:qa7v5ZcPASN/+OLk0RBCnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
