---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster-secrets.sops.yaml
  - ./sops-age.sops.yaml
  - ./keycloak-admin.sops.yaml
  - ./keycloak-db.sops.yaml
  - ./keycloak-db-owner.sops.yaml
