apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:8DegphB0avFSAx67uXV9JI49w7BboiXkyhFs3rmwYQxxPhKQMuxqGI3C3o/GxhmAnj0q8eJEQKNh7wC7QfXtQ4/oQvk8KcCNRHpbZc4mjUnukQhV8SFCb9rWWa011oBG/UKp0G+8bdX3cX4F/+lB+T0PVlkCf0cpQGizQrwUO9P2Ar2LS9+JdYorkwTyEaGImFMM11ubbjI536gCT4LG9IRhqFE4tU2FPFh1NF0JFbKurCChQ2NnLVsifgfDYXpjMmMWA+pH11irsDqXkLMSQQgveFeo1udik2BbT8TDYJJ3r6an6DOzwxluufZdfKjN0gkgzaognmVUBrNHsucGgKZdw2Dkp1OpAdMyE3a6+DoXlbVRYXveP0vNH5W9wqg+EqnNGU1J7rukLlq6ihVAyQYhWI5kDf6UsK9xYkyESb9ts4hYwbuh8s8G0KsLIsTJV4hpV59B8S6GlI0o9f6e0Mi5RFPZWTJ8AVbmTkp195uOrvI3Q5gBqg5QzOsJ9HZPECdDcqXGLe+g5fkiLN/gp/xhADzAJG34DEcZJr93xm1H6Nk/mKxbsJZq87uAzij11vZv1qxmxj7tAZJLfc4KrbEDm/q21Ezlub8ncsloelEc50u+zzxRwpyUJWo9gl5aheC5JAhd71Cx6SKr4e2s78hf2bhTAEJkPrXlfalmwbiNDkL/YQu2hzr7j/2R4ugrPY/30eGvojG55Bx6pLd+LGLukjgC/rR5FIp26RLr+hiDKQYGklJ1GLSzT5fvlkdhUKTI6PQ/w2MPcA0CNylzEjivv6utp/9WWaPAFm09DFf9/yEMjkR9bf0YqAf6MzovRQC7S/aODxpG4O24PuEHKSa8WXPGkyOH64LpEIsnl0/soZiL4Nnnr2lpLRF8mYvlDCQ2jLgisE/Rd6NxzcHzcLXC4IhOKeg+tPcpPhlI3nRfuf9BoC2l+feN9OAVA9gN3WpL+1mC1vvxq6JcCu7nbRQJmRFemGB8a++726CMt1cIyCkhvqDRHYjt2oZqBVIJBhJ6V6qLvXhb6J/H2cVQAmzyUIME733F69SRmj/HhPEEd5cMLkASAwryNVKNuv0wvRFr1xyuBjgq8D5IG0+UX/m0hkPgDUX7FTItmFrQgJxwS6XYiiF0/henTpUCXIJdm7MN6EhRrnJBk2TVEsaq4YjS81XDgqTo4ZHB/L75FyahwBXfMWy5aEUobkiBIKs0Ud9JXoAkMCj1xipargoCDnpiOOwqAo8D5Y045+5nLiJTfYJPdkdy5eaOCi8rezUijpgSDf+jy5TkK4chP4YCSzJHp2y41Kd3QNNYlJojoiip3LU/CZW5nX++8+zA5yJHHV4=,iv:SUVX6vTw+K4Uau+F1q/hu63TcEQd6ufCGRKfn0NPj1I=,tag:IDL/B7yTs4honr+jnU5FIg==,type:str]
sops:
    age:
        - recipient: age19tvjegxtk6e4gef3km9ns96uhhhvdrda3n04kv0g5sf0mggal40shfwzc9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNjhZYjc1M05aNGE3R3lW
            dzRNT05FRVNndWZZMHNiMERwR1BFZDBIOTNBClNzQ0QzQ3VxSGs5Q2hVbks4M3ht
            dEV3WkVpd29FcXNHVDhyWnEwaDlzVW8KLS0tIFc0Ykt6dlQ1K2l4dy9BdzFWb3ZP
            ZVNmSTl3cytTMXhxTzhwL3hZNHdoSE0K2VJhebmiuTLp29eB2Xjnz1M0IpRBLqOZ
            TGOWfRb10BeG5nQB879WtGmAdCr8exeHIk02ZoRxwm7WhhkIEZHHfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T18:02:43Z"
    mac: ENC[AES256_GCM,data:WdA9fOeq1cq93ZNctBELLmMf+I8Yf5JNXhpOk0pE9oczDRIbgf34aymJR08Mcub0OLzs8/WWLvmupigPXB4h+I+QbyZkgfyeSZdZrjx0D318Yd91Rp2DBs3xTLx5FMti4meb/a395UC/mxQj+9x8LrXALwOKLlpmmLFj+58IGsI=,iv:Hv9mwXgnE4hANNxvRhO1KZ82p4PXDTMbmZy5cpxSfQI=,tag:N2tdD0J+zT5tBD0LqpRmqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
