---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pg-sample-pgbouncer
  namespace: default
spec:
  cluster:
    name: pg-sample
  instances: 1
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters: {}

