---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"
  # Disable HTTP/2 to origin to avoid any websocket/upgrade quirks
  http2Origin: false

ingress:
  # Route ALL hosts (including plex) via the external gateway so
  # HTTPRoute filters can inject X-Forwarded-* headers Plex expects.
  # This avoids the "Plex page never loads" issue seen when bypassing
  # the Gateway and going directly to the Service.
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - service: http_status:404
