---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  suspend: false
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      plex:
        strategy: Recreate
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
          securityContext:
            supplementalGroups: [44, 107]
        containers:
          app:
            image:
              repository: plexinc/pms-docker
              tag: 1.42.1.10060-4e8b05daf # example, adjust as desired
            env:
              TZ: "UTC"
              ADVERTISE_IP: "https://plex.${SECRET_DOMAIN}:443"
            # No auto-claim; claim via Web UI after first start
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
                add: ["CHOWN", "SETUID", "SETGID"]
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            # Mounts are managed via persistence.* (no manual volumeMounts)

          rclone:
            image:
              repository: rclone/rclone
              tag: 1.67.0
            args:
              - mount
              - "gdrive:"
              - /mnt/media
              - --config=/config/rclone/rclone.conf
              - --umask=002
              - --dir-cache-time=1h
              - --poll-interval=1m
              - --allow-other
              - --allow-non-empty
              - --vfs-cache-mode=full
              - --vfs-read-ahead=64M
              - --buffer-size=32M
            securityContext:
              privileged: true      # required for FUSE
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
            # Mounts are managed via persistence.* (no manual volumeMounts)

    persistence:
      # Plex config on Longhorn (RWO)
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
        globalMounts:
          - path: /config

      # Shared emptyDir for rclone mount -> Plex media
      media:
        enabled: true
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /data/media
                readOnly: true
                mountPropagation: HostToContainer
            rclone:
              - path: /mnt/media
                mountPropagation: Bidirectional

      # Secret with rclone.conf providing a remote named `gdrive`
      rclone-config:
        enabled: true
        type: secret
        name: rclone-config
        defaultMode: 0400
        advancedMounts:
          plex:
            rclone:
              - path: /config/rclone
                readOnly: true

      # Mount /dev/fuse for rclone and /dev/dri for Plex iGPU transcoding
      fuse:
        enabled: true
        type: hostPath
        hostPath: /dev/fuse
        advancedMounts:
          plex:
            rclone:
              - path: /dev/fuse
      gpu:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
        advancedMounts:
          plex:
            app:
              - path: /dev/dri
                readOnly: true

    service:
      app:
        controller: plex
        ports:
          http:
            port: 32400

    # HTTPRoute is defined separately in app/httproute.yaml
