---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: monitoring
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: tempo
  interval: 1h
  path: ./kubernetes/apps/monitoring/tempo/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  timeout: 5m
  wait: false

